name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Shell Script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 108.61.224.32
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /basel
            git pull
            # Client
            cd /basel/client
            npm i
            npm run build
            cd /basel/server
            sqlx migrate run
            pm2 restart all
