name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Shell Script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 108.61.224.32
          username: root
          key: ${{ secrets.SSH_PROD }}
          script: |
            cd /root/basel.bot
            git pull
            # Client
            cd /root/basel.bot/client
            /root/.nvm/versions/node/v22.11.0/bin/npm i
            /root/.nvm/versions/node/v22.11.0/bin/npm run build
            cd /root/basel.bot/server
            /root/.cargo/bin/sqlx migrate run
            /root/.nvm/versions/node/v22.11.0/bin/pm2 restart all
